packages:
  - apps/*
  - examples/*
  - packages/*
  - templates/*
  - tests/*
  - docs

catalog:
  '@rsbuild/core': ^1.3.3
  '@rsbuild/plugin-babel': ^1.0.4
  '@rsbuild/plugin-react': ^1.1.1
  '@rsbuild/plugin-solid': ^1.0.5
  '@rsbuild/plugin-svelte': ^1.0.8
  '@rsbuild/plugin-vue': ^1.0.7
  '@rspack/core': ^1.3.2
