packages:
  - apps/*
  - examples/*
  - packages/*
  - tests/*
  - docs

catalog:
  '@rsbuild/core': 1.0.1-beta.9
  '@rsbuild/plugin-babel': 1.0.1-beta.9
  '@rsbuild/plugin-less': 1.0.1-beta.9
  '@rsbuild/plugin-react': 1.0.1-beta.9
  '@rsbuild/plugin-solid': 1.0.1-beta.9
  '@rsbuild/plugin-svelte': 1.0.1-beta.9
  '@rsbuild/plugin-vue': 1.0.1-beta.9
  '@rspack/core': 1.0.0-beta.1
