packages:
  - apps/*
  - examples/*
  - packages/*
  - tests/*
  - docs

catalog:
  '@rsbuild/core': ^1.0.2
  '@rsbuild/plugin-babel': ^1.0.1
  '@rsbuild/plugin-less': ^1.0.1
  '@rsbuild/plugin-react': ^1.0.1
  '@rsbuild/plugin-solid': ^1.0.1
  '@rsbuild/plugin-svelte': ^1.0.1
  '@rsbuild/plugin-vue': ^1.0.1
  '@rspack/core': ^1.0.4
