packages:
  - apps/*
  - examples/*
  - packages/*
  - tests/*
  - docs

catalog:
  '@rsbuild/core': ^0.7.10
  '@rsbuild/plugin-less': ^0.7.10
  '@rsbuild/plugin-react': ^0.7.10
  '@rsbuild/plugin-solid': ^0.7.10
  '@rsbuild/plugin-svelte': ^0.7.10
  '@rsbuild/plugin-vue': ^0.7.10
  '@rsbuild/shared': ^0.7.10
  '@rspack/core': ^0.7.5
